-
  name: Service Playbook
  hosts: localhost
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: ensure WORKING_DIR exists
      file:
        path: "{{ WORKING_DIR }}"
        state: directory

    - name: "Local Broker Setup"
      include_role:
        name: solace.pubsub_plus.solace_broker_service
      vars:
        project_name: broker_service_single_node
        state: present

    - name: "Save generated inventory"
      copy:
        content: "{{ solace_broker_service_result.broker_service.inventory | to_nice_yaml(indent=2) }}"
        dest: "{{ WORKING_DIR }}/broker.inventory.yml"
